"""rename address

Revision ID: 04339d81b9ff
Revises: 967b11abe834
Create Date: 2025-06-17 18:31:40.006859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04339d81b9ff'
down_revision = '967b11abe834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
