"""rename department

Revision ID: 967b11abe834
Revises: 5cd777126a1b
Create Date: 2025-06-17 18:24:39.127126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967b11abe834'
down_revision = '5cd777126a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
     op.rename_table('departments', 'department')
    
    # ### end Alembic commands ###
